const NAME= 'krph_uat';



export const STORE_PROCEDURE = {
    
    BM_USER_LOGIN: `${NAME}.bm_user_login`,
    FGMS_SEND_ESCALATION_MAIL: `${NAME}.fgms_send_escalation_mail`,
    FGMS_SEND_ESCALATION_MAIL_COMPLAINT: `${NAME}.fgms_send_escalation_mail_complaint`,    
    FGMS_ESCALATION_TICKET_DETAIL_INSERT: `${NAME}.fgms_escalation_ticket_detail_insert`,  
    FGMS_UPLOAD_INVOICE_DATA_INSERT: `${NAME}.fgms_upload_invoice_data_insert`,     
    FGMS_UPLOAD_INVOICE_DATA_SELECT: `${NAME}.fgms_upload_invoice_data_select`,     
    FGMS_SEND_ESCALATION_MAIL_COMPLAINT_SELECT: `${NAME}.fgms_send_escalation_mail_complaint_select`,    
    BM_APP_LOGOUT_USER: `${NAME}.bm_app_logout_user`,
    BM_APP_SALT_SESSION_INSERT: `${NAME}.bm_app_salt_session_insert`,
    BM_APP_SALT_SESSION_SELECT: `${NAME}.bm_app_salt_session_select`,    
    BM_APACCESS_FORGOT_PASSWORD: `${NAME}.bm_apaccess_forgot_password`,
    BM_APACCESS_VALIDATE_OTP: `${NAME}.bm_apaccess_validate_otp`,
    BM_USER_LOGIN_MENU_LIST: `${NAME}.bm_user_login_menu_list`,
    BM_USER_LIST: `${NAME}.bm_user_select_node`,
    BM_USER_CREATE: `${NAME}.bm_appaccess_insert_node`,
    BM_DIFF_USER_LOGIN: `${NAME}.bm_diff_user_login`,
    FGMS_BANK_USER_MASTER_INSERT: `${NAME}.fgms_bank_user_master_insert`,
    BM_USER_STATUS_UPDATE: `${NAME}.bm_user_update_status`,
    BM_USER_PASSWORD_FORGETRESET: `${NAME}.bm_apaccess_forgetreset_password_node`,    
    BM_USER_PASSWORD_RESET: `${NAME}.bm_apaccess_reset_password_node`,
    PASSWORD_OTP_SMS_HISTORY_INSERT: `${NAME}.password_otp_sms_history_insert`,
    USER_STATE_ASSIGN: `${NAME}.user_state_assign_manage_node`,
    USER_DISTRICT_ASSIGN: `${NAME}.user_district_assign_manage_node`,
    USER_SUBDISTRICT_ASSIGN: `${NAME}.user_subdistrict_assign_manage_node`,
    USER_BLOCK_ASSIGN: `${NAME}.user_block_assign_manage_node`,
    USER_INSURANCE_ASSIGN_MANAGE: `${NAME}.user_insurance_assign_manage_node`,
    USER_PROFILE_MENU_ASSIGN_MANAGE: `${NAME}.user_profile_menu_assign_manage_node`,
    USER_CATEGORY_ASSIGN_MANAGE: `${NAME}.user_category_assign_manage_node`,
    MENU_MASTER_CREATE: `${NAME}.menu_master_insert`,
    MENU_MASTER_MANEGE: `${NAME}.menu_master_manage`,
    MENU_USER_ASSIGN: `${NAME}.menu_user_assign_select`,
     SUPPORT_TICKET_USER_DETAIL: `${NAME}.support_ticket_user_detail`,
    SUPPORT_TICKET_MONGODB_SYNC: `${NAME}.fetch_support_ticket_mongodb_sync`,
   
    MASTER_DATA_BINDING: `${NAME}.app_master_data_binding`,
    LOCATION_MASTER_DATA_BINDING: `${NAME}.app_location_data_binding`,
    REGIONAL_OFFICE_SELECT: `${NAME}.regional_office_master_select`,
    REGIONAL_OFFICE_INSERT: `${NAME}.regional_office_master_insert`,
    REGIONAL_STATE_ASSIGN_MANAGE: `${NAME}.regional_state_assignment_manage`,
    REGIONAL_STATE_USER_ASSIGN_MANAGE: `${NAME}.user_regional_assign_manage`,        
    INSURANCE_USER_ASSIGN_TICKET : `${NAME}.assign_bulk_insurance_ticket_user_testmanual`,
    SUPPORT_TICKET_HISTRORY_REPORT : `${NAME}.support_ticket_history_report`,
    SUPPORT_TICKET_AGEING_REPORT_DETAIL: `${NAME}.support_ticket_ageing_report_detail_single`,
      SUPPORT_TICKET_HISTORY_SELECT: `${NAME}.support_ticket_history_csc_review_select`,
    SUPPORT_TICKET_CSC_REVIEW_INSERT: `${NAME}.support_ticket_csc_review_insert`,
    SUPPORT_TICKET_OFFLINE_GENERATE_INSERT: `${NAME}.support_ticket_offline_crop_loss_intimation_insert`,
    SUPPORT_TICKET_OFFLINE_GENERATE_SELECT: `${NAME}.support_ticket_offline_crop_loss_intimation_select`,
    
ALL_TICKET_LISTING_UNASSIGNED : `${NAME}.unassignedTicketView_csc`,
    AGENT_LIST_TICKET_COUNT : `${NAME}.agent_list_Tickets`,
    AGENT_WISE_TICKET_LIST:`${NAME}.agent_wise_ticket_listing`,
    INSURANCE_USER_UNASSIGN_TICKET : `${NAME}.unassign_bulk_insurance_ticket_user`,
    DASHBOARD_SELECT: `${NAME}.fgms_dashboard_func`,
    DASHBOARD_INSURANCE_SELECT: `${NAME}.fgms_dashboard_insurance_func`,
    SUPPORT_TICKET_VIEW_CSC_INDEX: `${NAME}.support_ticket_viewticket_csc_index`,
    SUPPORT_TICKET_STATUS_CHATBOT: `${NAME}.farmer_support_ticket_status_chatbot`,
    
    FARMER_LOGIN_SUPPORT_TICKET_INSERT: `${NAME}.farmer_login_support_ticket_insert`,
    FARMER_LOGIN_SUPPORT_TICKET_VIEW_CSC_INDEX: `${NAME}.farmer_login_support_ticket_viewticket_csc_index`,
    USER_PROFILE_RIGHTS_SELECT: `${NAME}.user_profile_rights_select`,
    USER_PROFILE_RIGHTS: `${NAME}.fgms_user_right_select`,
    USER_PROFILE_RIGHTS_MANAGE: `${NAME}.user_profile_rights_assign_manage_node`,
    SUPPORT_TICKET_VIEW_CSC: `${NAME}.support_ticket_viewticket_csc`,
    SUPPORT_TICKET_VOICE_BOT_HISTORY_INSERT: `${NAME}.support_ticket_voice_bot_history_insert`,
    SUPPORT_CSC_INBOUND_VOICE_BOT_HISTORY_INSERT: `${NAME}.support_csc_inbound_voice_bot_history_insert`,
    SUPPORT_CSC_INBOUND_VOICE_BOT_HISTORY_SELECT: `${NAME}.support_csc_inbound_voice_bot_history_select`,
    
    SUPPORT_BULK_TICKET_VIEW_CSC: `${NAME}.support_bulk_ticket_view_csc`,
    SUPPORT_TICKET_HISTORY_EXCEL_INSERT: `${NAME}.support_ticket_history_excel_insert`,
    
    SUPPORT_FARMERTICKET_VIEW_CSC: `${NAME}.support_farmerticket_viewticket_csc`,
    
    SUPPORT_TICKET_VIEW_INSURANCE: `${NAME}.support_ticket_viewticket_insurance`,
    SUPPORT_TICKET_INSERT: `${NAME}.support_ticket_insert`,
    FGMS_FARMERS_SUPPORT_TICKET_INSERT: `${NAME}.fgms_farmers_support_ticket_insert`,    
    SUPPORT_TICKET_GENERATE_INSERT: `${NAME}.support_ticket_insert`,
    SUPPORT_TICKET_LATEST_INSERT: `${NAME}.support_ticket_insert_latest`,
    SUPPORT_TICKET_STATUS_UPDATE: `${NAME}.support_ticket_status_update`,
 
    FARMER_SUPPORT_TICKET_STATUS_UPDATE: `${NAME}.farmer_support_ticket_status_update`,    
    SUPPORT_TICKET_HISTORY_SELECTTT: `${NAME}.support_ticket_history_select`,
    SUPPORT_TICKET_HISTORY_INSERT: `${NAME}.support_ticket_history_insert`,
    SUPPORT_TICKET_COMMENT_HISTORY_INSERT: `${NAME}.support_ticket_comment_history_insert`,    
    SUPPORT_BULK_TICKET_HISTORY_INSERT: `${NAME}.support_bulk_ticket_history_insert`,
    
    FARMERS_SUPPORT_TICKET_HISTORY_INSERT: `${NAME}.farmers_support_ticket_history_insert`,
    FARMERS_SUPPORT_TICKET_HISTORY_SELECT: `${NAME}.farmers_support_ticket_history_select`,
    SUPPORT_SMS_HISTORY_INSERT: `${NAME}.support_sms_history_insert`,
    FARMER_SUPPORT_SMS_HISTORY_INSERT: `${NAME}.farmer_support_sms_history_insert`,
    SUPPORT_TICKET_CAT_REPORT: `${NAME}.support_ticket_category_report`,
    SUPPORT_TICKET_AGEING_REPORT: `${NAME}.support_ticket_ageing_report`,
    SUPPORT_TICKET_DETAIL_REPORT: `${NAME}.support_ticket_details`,
    SUPPORT_TICKET_REOPEN_DETAIL_REPORT: `${NAME}.support_ticket_reopen_details`,
    TICKET_BINDING_SELECT: `${NAME}.ticket_binding_select`,
    FARMERS_CALLING_MASTER_INSERT: `${NAME}.farmers_calling_master_insert`,
    FARMERS_CALLING_MASTER_SELECT: `${NAME}.farmers_calling_master_select`,
    FGMS_FARMERS_MASTER_SELECT: `${NAME}.fgms_farmers_master_select`,
    FGMS_FARMERS_MASTER_INSERT: `${NAME}.fgms_farmers_master_insert`,
    FGMS_FARMERS_MASTER_UPDATE: `${NAME}.fgms_farmers_master_update`,
    ENQUIRY_TICKET_HISTORY_INSERT: `${NAME}.enquiry_ticket_history_insert`,
    ENQUIRY_TICKET_HISTORY_SELECT: `${NAME}.enquiry_ticket_history_select`,

    USER_PROFILE_MASTER_SELECT: `${NAME}.user_profile_master_select`,
    ADD_PROFILE_MASTER_SELECT: `${NAME}.user_profile_master_insert`,
    USER_PROFILE_ASSIGN_MANAGE: `${NAME}.user_profile_assign_manage_node`,

    BM_USER_CREATE_NODE: `${NAME}.bm_appaccess_insert_node`,
    BM_USER_LOGIN_NODE: `${NAME}.bm_user_login_node`,
    SUPPORT_TICKET_CROP_LOSS_DETAIL: `${NAME}.support_ticket_crop_loss_detail`,
    FGMS_PREMIUM_CALCULATORY_HISTORY_INSERT: `${NAME}.fgms_premium_calculatory_history_insert`,
    FGMS_PREMIUM_CALCULATORY_HISTORY_REPORT: `${NAME}.fgms_premium_calculatory_history_report`,

    FGMS_USER_ASSIGNED_TICKET_LIST:`${NAME}.assignedTicketView_csc_index`
    
};
